# Generated by Django 4.1 on 2022-08-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('lofter', models.CharField(max_length=50)),
                ('fodt', models.IntegerField()),
                ('aar', models.IntegerField()),
                ('mnd', models.IntegerField()),
                ('dag', models.IntegerField()),
                ('vekt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kat', models.CharField(max_length=50)),
                ('rykk', models.IntegerField()),
                ('stot', models.IntegerField()),
                ('sml', models.IntegerField()),
                ('sinclair', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tau', models.IntegerField()),
                ('klubb', models.CharField(max_length=50)),
                ('stevne', models.CharField(max_length=50)),
            ],
        ),
    ]
