# Generated by Django 4.1 on 2022-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='tau',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
